[package]
authors = ["h.abedijoo@gmail.com"]
edition = "2020"
name = "tags"
version = "0.0.1"

[lib]
crate-type = ["cdylib", "rlib"]
name = "tags"

[dependencies]
derive_more = "0"
serde = "1"

hdk3 = {git = "https://github.com/holochain/holochain", rev = "4714fbd", package = "hdk3"}
