[package]
authors = ["h.abedijoo@gmail.com"]
edition = "2018"
name = "peershare"
version = "0.0.1"

[lib]
crate-type = ["cdylib", "rlib"]
name = "peershare"


[dependencies]
derive_more = "0"
serde = "1"

hc_utils = "0"
hdk3 = "0"
